### ISSUE TITLE
Problem running template

### ISSUE THREAD

**Issue by lnfernandobr** [ixartz/Astro-boilerplate#8]
I ran the following commands:
```bash
git clone --depth=1 https://github.com/ixartz/Astro-boilerplate
cd Astro-boilerplate
npm install
npm run dev
```
I'm receiving this error:
```
> astro-boilerplate@1.0.0 dev /home/fernando/Documents/Empresa/Dev/Astro-boilerplate
> astro dev

(node:44380) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react-dom' imported from /home/fernando/Documents/Empresa/Dev/Astro-boilerplate/node_modules/@astrojs/react/dist/index.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:44380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/29682136/233179130-dcf91bcf-2046-4822-8138-ae456cd89caa.png)
![image](https://user-images.githubusercontent.com/29682136/233179160-ee16576a-38cd-4116-92ed-4bdc7a50d146.png)

**Comment by ixartz** [comment]
Thank @lnfernandobr for letting me know, I'll take a look and get back to you.

**Comment by ixartz** [comment]
@lnfernandobr, it works perfectly from a fresh and clean install on my side:
- npm install
- npm run dev

```sh
npm run dev

> astro-boilerplate@1.0.0 dev
> astro dev

  🚀  astro  v1.0.0-beta.44 started in 22ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

Could you add `npm install react-dom` before running `npm run dev`?
Does it solve the issue?

**Comment by antonybholmes** [comment]
package.json is missing the react and react-dom dependencies so the build won't work unless the user has react and react-dom install globally. You should update package.json to include these.

**Comment by ixartz** [comment]
@antonybholmes I just add react and react-dom in package.json file. Hope now it should solve the issue.
